services:
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=false"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyStrongPassword123!"
      - network.host=0.0.0.0
      - http.port=9200
      - transport.port=9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    # volumes:
    #   - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u admin:MyStrongPassword123! https://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=false"
      - "OPENSEARCH_HOSTS=https://opensearch:9200"
      - "OPENSEARCH_USERNAME=kibanaserver"
      - "OPENSEARCH_PASSWORD=kibanaserver"
      - "SERVER_NAME=opensearch-dashboards"
      - "SERVER_HOST=0.0.0.0"
    depends_on:
      - opensearch
    networks:
      - opensearch-net
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -u admin:MyStrongPassword123! -f http://localhost:5601/api/status || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 60s

  data-prepper:
    container_name: data-prepper
    image: opensearchproject/data-prepper:2.8.0
    volumes:
      - ./log_pipeline.yaml:/usr/share/data-prepper/pipelines/log_pipeline.yaml
    ports:
      - 2021:2021
    depends_on:
      - opensearch
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:2021/log/ingest -X POST -d '[]' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:3.0
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./data-ingestion/nginx/access.log:/var/log/access.log
    depends_on:
      - data-prepper
    networks:
      - opensearch-net

# volumes:
#   opensearch-data:

networks:
  opensearch-net: